server:
  port:

spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
